# Site settings
title: MC.Info
subtitle: code, audio, and life developments by michael chadwick
author: Michael Chadwick
extra_title: ' | home of audio dev michael chadwick'
email: mike@neb.host
description: 'code, audio, and life developments by michael chadwick'
description_html: "code, audio, and life of <a href='/'>michael chadwick</a>"
description_short: 'code, audio, life'
url: 'https://michaelchadwick.info'
home_relative_url: '/'
blogurl: '/blog'
encoding: UTF-8
exclude: ['Rakefile', '.deploy.sh', '.env.example']
include: ['mus.html', 'net.html', 'index_print.html', '.env']
webrick:
  headers:
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: 'POST, GET, OPTIONS'
tag_page_layout: tag_page
tag_page_dir: blog/tags
enable_comments: true
date_YYYYMMDD_dash: '%Y-%m-%d'
date_YYYYMMDD_slash: '%Y/%m/%d'
date_MMDDYYYY: '%b %-d, %Y'
date_YYYYMD: '%Y-%m-%d'
date_YYYY: '%Y'

plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-paginate-v2
  # - jekyll-tagging # here for ref; uncommenting breaks jekyll build for some reason
  - jekyll-thumbnail-img
  - jekyll-timeago
  - jemoji
# Plugin settings
jekyll_admin:
  hidden_links:
    - staticfiles
    - datafiles
jekyll_timeago:
  depth: 2
  default_locale: 'en'
  fallbacks: true
feed:
  disable_in_development: true
pagination:
  enabled: true
  per_page: 20
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
permalink: pretty

# Custom Site settings
gh_username: michaelchadwick
tw_username: mjchadwick
masto_username: nebyoolae
linkedin_username: michaeljchadwick
sc_n_username: nebyoolae
sc_mb_username: massive-battery
bc_username: nebyoolae
mc_link: https://michaelchadwick.info
neb_link: https://nebyoolae.com
gh_link: https://github.com/michaelchadwick
masto_link: https://masto.neb.host/@nebyoolae
linkedin_link: https://www.linkedin.com/in/michaeljchadwick
htg_link: https://hackingthegrepson.com
# soundcloud
sc_neb_link: https://soundcloud.com/nebyoolae
sc_mb_link: https://soundcloud.com/massive-battery
# bandcamp
bc_neb_link: https://nebyoolae.bandcamp.com
bc_flv_link: https://flylikevenus.bandcamp.com
bc_fenchy_link: https://fenchy.bandcamp.com
bc_pyc_link: https://pureyellow.bandcamp.com
bc_rc_link: https://rustycrab.bandcamp.com
# spotify
sp_neb_link: https://open.spotify.com/artist/5S1HHS8jWDcQKXuAfHlmFw?si=HhedVBtsTZW-b5yAXkEYwA
sp_fenchy_link: https://open.spotify.com/artist/6txteNrnvTbRUb9sUOeAVM?si=w-bXjrb2QVeIbsSwrhTO4g
sp_flv_link: https://open.spotify.com/artist/0UTm3Fpds4BVrvSFIGj2iD?si=aIM4rCgzTiOYyrzTONkf-g
sp_pyc_link: https://open.spotify.com/artist/6a5qMaB4YKI6A1umEH7IFj
# apple music
am_neb_link: https://music.apple.com/us/artist/nebyoolae/1655123042
am_fenchy_link: https://music.apple.com/us/artist/fenchy/1652676694
am_flv_link: https://music.apple.com/us/artist/fly-like-venus/1250934211
am_pyc_link: https://music.apple.com/us/artist/pure-yellow-colour/279571891
# youtube music
yt_neb_link: https://music.youtube.com/channel/UCD9SVVjQptRCasX5Dmgki5Q
yt_fenchy_link: https://music.youtube.com/channel/UCFpxTtf0D_8bGQQoLcw7pjA
yt_flv_link: https://music.youtube.com/channel/UCZM6OHNCjdvKJvjseMNVihA
yt_pyc_link: https://music.youtube.com/channel/UCo9sfG61EnT8MO205DhzEWg
